// Generated by CoffeeScript 1.6.2
var Todo, fs, program;

program = require('commander');

fs = require('fs');

Todo = require('./todo');

program.version('0.1.1').option('-n, --name [name]', 'Set name').option('-d, --date [date]', 'Set date').option('-D, --done', 'Flag done TODOs').option('-U, --undone', 'Flag undone TODOs');

program.command('new').description('Creates a new TODO and add it to the list').action(function() {
  if (program.name) {
    new Todo({
      name: program.name,
      date: program.date
    });
  }
  Todo.show();
  return Todo.save();
});

program.command('remove').description('Remove TODOs from the list').action(function() {
  Todo.remove({
    name: program.name,
    date: program.date,
    done: program.done
  });
  Todo.show();
  return Todo.save();
});

program.command('set').description('Set TODOs as done/undone').action(function(name) {
  if (!program.done && !program.undone) {
    console.log("Done/Undone flag not specified");
    return;
  }
  Todo.done({
    name: program.name,
    date: program.date,
    done: program.done || !program.undone
  });
  Todo.show();
  return Todo.save();
});

program.command('clean').description('Remove done TODOs from the list').action(function() {
  Todo.remove({
    done: true
  });
  Todo.show();
  return Todo.save();
});

program.command('*').description('Show the TODOs list').action(Todo.show);

Todo.load(function() {
  program.parse(process.argv);
  if (process.argv.length <= 2) {
    return Todo.show();
  }
});
