// Generated by CoffeeScript 1.6.2
var Today, Todo, colors, fs, moment;

moment = require('moment');

colors = require('colors');

fs = require('fs');

Today = moment();

Todo = (function() {
  Todo.all = [];

  Todo.show = function() {
    var todo, _i, _len, _ref;

    this.all.sort(function(a, b) {
      if (a.type === b.type) {
        return a.name > b.name;
      }
      return a.type > b.type;
    });
    _ref = this.all;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      todo = _ref[_i];
      console.log("" + todo);
    }
    if (this.all.length < 1) {
      return console.log("nothing to do".grey);
    }
  };

  Todo.remove = function(options) {
    var _this = this;

    return this.all.forEach(function(todo, index) {
      if ((options.name && todo.name.match(options.name)) || (options.date && todo.date.format("DD/MM/YYYY").match(options.date)) || (options.done && todo.done)) {
        delete _this.all[index];
        return _this.all.splice(index, 1);
      }
    });
  };

  Todo.done = function(options) {
    var _this = this;

    return this.all.forEach(function(todo) {
      if ((options.name && todo.name.match(options.name)) || (options.date && todo.date.format("DD/MM/YYYY").match(options.date))) {
        return todo.done = true;
      }
    });
  };

  Todo.save = function() {
    return fs.writeFile('todos.json', JSON.stringify(this.all.map(function(e) {
      return e.toJSON();
    })), function(err) {
      if (err) {
        throw err;
      }
    });
  };

  function Todo(options) {
    var _ref;

    if (options == null) {
      options = {};
    }
    this.type = options.type;
    if (this.type) {
      this.name = options.name;
    } else {
      _ref = options.name.split(':'), this.type = _ref[0], this.name = _ref[1];
      if (!this.name) {
        this.name = this.type;
        delete this.type;
      }
    }
    this.name = this.name.trim();
    if (options.date) {
      this.date = moment(options.date, "DD-MM-YYYY");
    }
    this.done = options.done || false;
    Todo.all.push(this);
  }

  Todo.prototype.toString = function() {
    var str;

    str = this.name;
    str = (this.type ? "" + this.type + ": " : "") + str;
    if (this.done) {
      return str.strike.green;
    }
    if (this.date) {
      str += " - " + (this.date.format("DD/MM/YYYY"));
      if (this.date.date() < Today.date()) {
        return str.underline.red;
      }
      if (this.date.date() === Today.date()) {
        return str.bold.yellow;
      }
    }
    return str;
  };

  Todo.prototype.toJSON = function() {
    return {
      type: this.type,
      name: this.name,
      date: (this.date ? this.date.format("DD/MM/YYYY") : void 0),
      done: this.done
    };
  };

  return Todo;

})();

module.exports = Todo;
